In [27]:
import tkinter as tk
from tkinter import filedialog
import json
import numpy as np
root = tk.Tk()
root.attributes("-topmost", True)
root.withdraw()

file_path = filedialog.askopenfilename(title = "Choose the position list", initialdir = "D:/Experiments/MUSCLE DONUTS/20220824_FC_Nano_Cas9_CCR5/parameter")
pos_file = open(file_path)
data = json.load(pos_file)
POS = data['POSITIONS']

labels = [P['LABEL'] for P in POS]
posX = [P['DEVICES'][0]['X'] for P in POS]
posY = [P['DEVICES'][0]['Y'] for P in POS]

In [9]:
# x0 = 28523
# y0 = -1313
# idx = []
# for i,lab in enumerate(labels):
#     if abs(posX[i]-x0)<200 and abs(posY[i]-y0)<200:
#         idx.append(lab)


In [47]:

# x1 = [posX[i] for i,x in enumerate(labels) if labels[i]=='Pos246']
# y1 = [posY[i] for i,x in enumerate(labels) if labels[i]=='Pos246']
# print(x1, y1)
# # x1_old = [posX[i] for i,x in enumerate(labels) if labels[i]=='Pos246']
# # y1_old = [posY[i] for i,x in enumerate(labels) if labels[i]=='Pos246']
    
# # print(2329+(x1[0]-28523)/0.34)
# # print(2042-(y1[0]+1313)/0.34)

[28522.9] [-1313.3000000000002]


In [52]:
# x1 = [posX[i] for i,x in enumerate(labels) if labels[i]=='Pos129']
# y1 = [posY[i] for i,x in enumerate(labels) if labels[i]=='Pos129']
# print(x1, y1)

[26824] [-1187.1000000000001]


In [58]:
# idx = [i for i,x in enumerate(labels) if labels[i]=='Pos129' or labels[i]=='Pos130']
# T = [posX[i] for i in idx]
# print(T)

[26824, 26714]


In [28]:
from skimage import transform
tr = transform.SimilarityTransform()
tr.params = np.array([[ 5.98278480e-01, -2.04811207e-03,  0],
 [ 2.04811207e-03,  5.98278480e-01,  0],
 [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])
tr_inv = transform.SimilarityTransform()
tr_inv.params = np.array([[ 1.67127284e+00,  5.72133913e-03,  0],
 [-5.72133913e-03,  1.67127284e+00,  0],
 [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

Make a composite image

In [29]:
import os.path as path
import skimage as si
import skimage.io as io


size1 = tr([[256,512]]).astype(int)
print(size1)

minx = min(posX)
maxx = max(posX)
miny = min(posY)
maxy = max(posY)

size = [maxy-miny+50+size1[0,0], maxx-minx+50+size1[0,1]]
size = np.divide(size,0.34).astype(int)
print(size)

img = np.zeros(size)

rb_rad = 10                               

[[152 306]]
[ 3241 10752]


In [30]:
red_path = filedialog.askdirectory(title = "Choose the bead directory", initialdir = "D:/Experiments/MUSCLE DONUTS/20220824_FC_Nano_Cas9_CCR5/parameter")

In [31]:
pos = labels[10]
path1 = path.join(red_path,pos,'A_Red','img_000000000.tiff')
img1 = io.imread(path1)
print(img1.shape)

(512, 512, 3)


In [32]:
for pos in labels:
    path1 = path.join(red_path,pos,'A_Red','img_000000000.tiff')
#     path1 = path.join(red_path,pos+'.tiff')
    if path.exists(path1):
        print(pos)
        img1 = io.imread(path1)
#         img1 = np.mean(img1, axis = 0)
        img1 = np.mean(img1, axis = 2)
        img1 = img1.astype("ushort")
        img1 = img1[256:,:]
        img1 = img1 - si.restoration.rolling_ball(img1, radius=rb_rad)
        img1 = transform.warp(img1, tr_inv, output_shape = size1[0])
        x1 = [posX[i] for i,x in enumerate(labels) if labels[i]==pos]
        y1 = [posY[i] for i,x in enumerate(labels) if labels[i]==pos]
        id1 = int((maxy-y1[0])/0.34)
        id2 = int((x1[0]-minx)/0.34)

        img[id1:id1+size1[0,0],id2:id2+size1[0,1]] = img1

Pos103
Pos104
Pos105
Pos106
Pos107
Pos108
Pos109
Pos110
Pos111
Pos112
Pos113
Pos114
Pos115
Pos116
Pos117
Pos118
Pos119
Pos120
Pos121
Pos122
Pos123
Pos124
Pos125
Pos126
Pos127
Pos128
Pos129
Pos130
Pos131
Pos132
Pos133
Pos136
Pos137
Pos138
Pos139
Pos140
Pos141
Pos142
Pos143
Pos144
Pos145
Pos146
Pos147
Pos148
Pos149
Pos150
Pos151
Pos152
Pos153
Pos154
Pos155
Pos156
Pos157
Pos158
Pos159
Pos160
Pos161
Pos162
Pos163
Pos164
Pos165
Pos166
Pos169
Pos170
Pos171
Pos172
Pos173
Pos174
Pos175
Pos176
Pos177
Pos178
Pos179
Pos180
Pos181
Pos182
Pos183
Pos184
Pos185
Pos186
Pos187
Pos188
Pos189
Pos190
Pos191
Pos192
Pos193
Pos194
Pos195
Pos196
Pos197
Pos198
Pos199
Pos202
Pos203
Pos204
Pos205
Pos206
Pos207
Pos208
Pos209
Pos210
Pos211
Pos212
Pos213
Pos214
Pos215
Pos216
Pos217
Pos218
Pos219
Pos220
Pos221
Pos222
Pos223
Pos224
Pos225
Pos226
Pos227
Pos228
Pos229
Pos230
Pos231
Pos232
Pos235
Pos236
Pos237
Pos238
Pos239
Pos240
Pos241
Pos242
Pos243
Pos244
Pos245
Pos246
Pos247
Pos248
Pos249
Pos250
Pos251
Pos252
Pos253

In [12]:
# pos = "Pos400"
# path1 = path.join(red_path,pos,'A_Red','img_000000000.tiff')
# img1 = io.imread(path1)

In [15]:
# img2 = np.mean(img1, axis = 2)
        
# print(img2.shape)

(512, 512)


In [33]:
from skimage.util import img_as_uint, img_as_ubyte
img2 = img_as_uint(img)
print(img2)
io.imsave(red_path+'/Combined.png',img2)

[[17 36 36 ...  0  0  0]
 [20 27 36 ...  0  0  0]
 [59 46 51 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


C:\Users\Anton\AppData\Local\Temp\ipykernel_6728\4008391470.py:4: UserWarning: D:/20221227_FC_Nano_Hairpin_peltier_Fix6 worked/All pos/Combined.png is a low contrast image
  io.imsave(red_path+'/Combined.png',img2)


In [78]:
pos = 'Pos120'
x1 = [posX[i] for i,x in enumerate(labels) if labels[i]==pos]
y1 = [posY[i] for i,x in enumerate(labels) if labels[i]==pos]
id1 = int((maxy-y1[0])/0.34)
id2 = int((x1[0]-minx)/0.34)
print(x1,y1,id1,id2,labels[0])

[27619.100000000002] [-1588.2] 2647 4205 Pos103


In [83]:
file_path_seq = filedialog.askopenfilename(title = "Choose the sequencing image", initialdir = "D:/Experiments/MUSCLE DONUTS/20220824_FC_Nano_Cas9_CCR5/parameter")

In [84]:
img3 = io.imread(file_path_seq)

In [85]:
import matplotlib.pyplot as plt
from skimage import data
from skimage import transform
from skimage.feature import match_descriptors, plot_matches, SIFT


descriptor_extractor = SIFT()

descriptor_extractor.detect_and_extract(img[1000:2000,1000:2000])
keypoints1 = descriptor_extractor.keypoints
descriptors1 = descriptor_extractor.descriptors

descriptor_extractor.detect_and_extract(img3)
keypoints2 = descriptor_extractor.keypoints
descriptors2 = descriptor_extractor.descriptors

# matches12 = match_descriptors(descriptors1, descriptors2, max_ratio=0.6,
#                               cross_check=True)
# matches13 = match_descriptors(descriptors1, descriptors3, max_ratio=0.6,
#                               cross_check=True)
# fig, ax = plt.subplots(nrows=2, ncols=2, figsize=(11, 8))

# plt.gray()

# plot_matches(ax[0, 0], img1, img2, keypoints1, keypoints2, matches12)
# ax[0, 0].axis('off')
# ax[0, 0].set_title("Original Image vs. Flipped Image\n"
#                    "(all keypoints and matches)")

# plot_matches(ax[1, 0], img1, img3, keypoints1, keypoints3, matches13)
# ax[1, 0].axis('off')
# ax[1, 0].set_title("Original Image vs. Transformed Image\n"
#                    "(all keypoints and matches)")

# plot_matches(ax[0, 1], img1, img2, keypoints1, keypoints2, matches12[::15],
#              only_matches=True)
# ax[0, 1].axis('off')
# ax[0, 1].set_title("Original Image vs. Flipped Image\n"
#                    "(subset of matches for visibility)")

# plot_matches(ax[1, 1], img1, img3, keypoints1, keypoints3, matches13[::15],
#              only_matches=True)
# ax[1, 1].axis('off')
# ax[1, 1].set_title("Original Image vs. Transformed Image\n"
# #                    "(subset of matches for visibility)")

# plt.tight_layout()
# plt.show()

MemoryError: Unable to allocate 1.51 GiB for an array with shape (6, 5888, 5732) and data type float64

In [82]:
print(descriptors1.shape)

(288, 128)
